rottenpotatoes/config/routes.rb
Rottenpotatoes::Application.routes.draw do
  devise_for :moviegoers, controllers:{
    sessions: 'moviegoers/sessions',
    omniauth_callbacks: 'moviegoers/omniauth_callbacks'
  }
  devise_scope :moviegoer do
    root to: "devise/sessions#new"
  end
  resources :movies
  # map '/' to be a redirect to '/movies'
  post '/movies/search_tmdb' => 'movies#search_tmdb', :as => 'search_tmdb'
end

rottenpotatoes/app/controllers/movies_controller.rb
require 'uri'
require 'net/http'
require 'json'

# MoviesController is responsible for feature associate with movie data
class MoviesController < ApplicationController
  
  # Display movie data via movieID params
  def show
    id = params[:id] # retrieve movie ID from URI route
    @movie = Movie.find(id) # look up movie by unique ID
    # will render app/views/movies/show.<extension> by default
  end

  # Display index page with movies data table with checkbox feature
  def index
    sort = params[:sort] || session[:sort]
    case sort
    when 'title'
      ordering,@title_header = {:title => :asc}, 'bg-warning hilite'
    when 'release_date'
      ordering,@date_header = {:release_date => :asc}, 'bg-warning hilite'
    end
    @selected_ratings = params[:ratings] || session[:ratings] || Hash[Movie.all_ratings.map {|rating| [rating, rating]}]
    if params[:sort] != session[:sort] or params[:ratings] != session[:ratings]
      session[:sort] = sort
      session[:ratings] = @selected_ratings
      redirect_to :sort => sort, :ratings => @selected_ratings and return
    end
    @movies = Movie.where(rating: @selected_ratings.keys).order(ordering)
  end

  # Display new template
  def new
    # default: render 'new' template
  end

  # Create data to Movie table
  def create
    @movie = Movie.create!(params[:movie])
    flash[:notice] = "#{@movie.title} was successfully created."
    redirect_to movies_path
  end

  # Get movie data via movie id
  def edit
    @movie = Movie.find params[:id]
  end

  # Update movie data specify via movie id
  def update
    @movie = Movie.find params[:id]
    @movie.update_attributes!(params[:movie])
    flash[:notice] = "#{@movie.title} was successfully updated."
    redirect_to movie_path(@movie)
  end

  # Delete movie row via movie id
  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    flash[:notice] = "Movie '#{@movie.title}' deleted."
    redirect_to movies_path
  end

  # Call TMDB API for movie data
  def tmdb_search_movie(movie_title)
    api_key = "fbc366092c54ff98967f908e634acd23"
    uri = URI("https://api.themoviedb.org/3/search/movie?api_key=#{api_key}&language=en-US&query=#{movie_title}&page=1&include_adult=false")
    res = Net::HTTP.get_response(uri)
    tmdb_results = JSON.parse(res.body)['results']
    tmdb_results
  end

  # Get movie data via title through TMDb api
  def search_tmdb
    title = params[:search_terms][:title]
    results = self.tmdb_search_movie(title)
    if results.length() == 0 #Sad path (no result found)
      flash[:notice] = "'Movie That Does Not Exist' was not found in TMDb."
      redirect_to movies_path
      return
    else
      item = results[0] #first result
      @movies = {
        "title" => item["title"],
        "release_date" => item["release_date"]
      }
      return
    end
  end

end

rottenpotatoes/app/views/movies/index.html.haml
-#  This file is app/views/movies/index.html.haml
%h2 All Movies

= form_tag movies_path,style: 'display: flex;align-items:center;margin-bottom:25px' ,:method => :get, :id => 'ratings_form' do
  = hidden_field_tag "title_sort", true if @title_header
  = hidden_field_tag ":release_date_sort", true if @date_header
  Include:
  - @all_ratings.each do |rating|
    = rating
    = check_box_tag "ratings[#{rating}]", 1, @selected_ratings.include?(rating), :id => "ratings_#{rating}",style: "margin-right:10px"
  = submit_tag 'Refresh', :id => 'ratings_submit', :class => 'btn btn-primary'
  - if current_moviegoer
    %div{style: 'float:right;width:auto;margin-left:auto;'}
      = link_to "Log out", destroy_moviegoer_session_path, :method => :delete 
      = image_tag(current_moviegoer.avatar_url,:alt => "profile_icon")

%table#movies.table.table-striped.col-md-12
  %thead
    %tr
      %th{:class => @title_header}= link_to 'Movie Title', movies_path(:sort => 'title', :ratings => @selected_ratings), :id => 'title_header'
      %th Rating
      %th{:class => @date_header}= link_to 'Release Date', movies_path(:sort => 'release_date', :ratings => @selected_ratings), :id => 'release_date_header'
      %th More Info
  %tbody
    - @movies.each do |movie|
      %tr
        %td= movie.title
        %td= movie.rating
        %td= movie.release_date
        %td= link_to "More about #{movie.title}", movie_path(movie)
        
= link_to 'Add new movie', new_movie_path

%h3 Search TMDb for a movie
= form_tag search_tmdb_path, :method => :post do

  = label :search_terms, :title, 'Search Terms'
  = text_field :search_terms, 'title'

  = submit_tag 'Search TMDb', :class => 'btn btn-primary'

rottenpotatoes/app/views/movies/search_tmdb.html.haml
%h2 Search result

= form_tag movies_path do

  = label :movie, :title, 'Title'
  %span#title= @movies["title"].capitalize
  = hidden_field :movie, 'title' , value: @movies["title"]

  = label :movie, :rating, 'Rating'
  = select :movie, :rating, ['G','PG','PG-13','R','NC-17']

  = label :movie, :release_date, 'Released On'
  = date_select :movie, :release_date , selected: Date.parse(@movies["release_date"])

  = submit_tag 'Save Changes', :class => 'btn btn-primary'